@startuml カレーライス
title カレーライス
start
fork
:玉ねぎの下処理をする;
:ニンジンの下処理をする;
:ジャガイモの下処理をする;
fork
:肉の下処理をする;
fork again
:鍋に火をつける;
fork end
:玉ねぎを炒める;
:肉を炒める;
:ジャガイモを入れる;
:ニンジンを入れる;
:水を入れて煮込む;
:カレールーを入れる;
fork again
:お米を炊く;
end fork
:盛りつける;
stop
@enduml